#!/usr/bin/env zsh
# script

doInstall() {
   if [ -e "/main" ]; then
	for files in /main/source-docs/*; do
	   source $files
	done
   else
	echo "Directory 'main' cannot be found"
   fi

   prov() {

	ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
	hwclock --systohc

	echo "LANG=en_US.UTF-8" >> /etc/locale.conf
	echo "en_US.UTF-8 UTF-8" >> /etc/locale.conf
	export LANG=en_US.UTF-8

   }
   prov

   getGrub() {

	pacman-key --init
	pacman-key --populate
	pacman -Sy ; pacman -Fy

	pacman -Syyu

   if [ ! -e "/usr/bin/grub-install" ]; then
      yes | pacman -S grub efibootmgr
   
   elif [ -e "/usr/bin/grub-install" ]; then
	grub-install /dev/nvme0n1
	grub-mkconfig -o /boot/grub/grub.cfg
   else
	echo "Grub not present"; exit 69
   fi


   }
   getGrub

   makeUsers() {

	groupadd me; groupadd admin
	useradd me -M -g me -G root,sys,wheel,admin -s /home -s /bin/zsh

	echo "me ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
	echo " %me ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
	echo " %root ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
	

   }
   makeUsers


   getPlasma() {
	
	cd /home 
	pacman -S plasma-plasma-desktop sddm konsole kate dolphin 


   }
   getPlasma

   provUsers() {
	
	echo "Setting password for root"; sleep 1
	passwd root
	echo "Setting password for User 'me' "; sleep 1
	passwd me
	chown -R me:me /home

   }
   provUsers

   getTheRest() {


   yes | pacman -S docker docker-compose composer fail2ban ufw inkscape gimp openssh openvpn
	

   }
   getTheRest

}

doInstall
